name: Run Cucumber Tests

on:
 workflow_dispatch:
  inputs:
   tag:
    description: "Cucumber tag to run"
    required: true
    default: "@smoke"
 
jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true  # Speeds up installs between runs

      - name: Show current directory
        run: pwd
        
      - name: List files in current directory
        run: ls -la
        
      - name: Install dependencies
        run: bundle install

      - name: List gems managed by Bundler
        run: bundle list
        
      - name: Start mock server
        run: |
          echo "Starting mock server..."
          bundle exec ruby mock_service/mock_hsi/mock_hsi_service.rb &
          sleep 3 # wait for the server to boot
          
      - name: Run Cucumber tests with JSON output
        run: | 
         echo "Running Cucumber with tag: ${{ github.event.inputs.tag }}"
         bundle exec cucumber --format json --out public/cucumber.json --tags ${{ github.event.inputs.tag }}

      - name: Generate HTML report
        run: |
          bundle exec ruby -e "
            require 'report_builder';
            ReportBuilder.configure do |config|
              config.input_path = 'public/cucumber.json';
              config.report_path = 'public/cucumber.html';
              config.report_types = [:html];
              config.color = 'blue';
            end;
            ReportBuilder.build_report
          "

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: public/cucumber.html

      - name: Stop mock server
        if: always()
        run: |
          echo "Stopping mock server..."
          pkill -f mock_service/mock_hsi/mock_hsi_service.rb || true        
