name: Run Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true  # Speeds up installs between runs

      - name: Install dependencies
        run: bundle install

      - name: Run Cucumber tests
        run: bundle exec cucumber
